version: "3"

services:
  # Nessie Catalog Server Using In-Memory Store
  q-nessie:
    image: projectnessie/nessie:latest
    container_name: q-nessie
    networks:
      - q-iceberg
    ports:
      - 19120:19120

  # MinIO Storage Server
  ## Creates two buckets named lakehouse and lake
  q-minio:
    image: minio/minio:latest
    container_name: q-minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    networks:
      - q-iceberg
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5 &&
      mc alias set myminio http://localhost:9000 admin password &&
      mc mb myminio/lakehouse &&
      mc mb myminio/lake &&
      tail -f /dev/null
      "

  # Dremio
  q-dremio:
    image: dremio/dremio-oss:latest
    container_name: q-dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      - q-iceberg
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010

  # Superset
  q-superset:
    image: alexmerced/dremio-superset
    container_name: q-superset
    networks:
      - q-iceberg
    ports:
      - 8088:8088

  # Data Science Notebook (Jupyter Notebook)
  q-datanotebook:
    image: alexmerced/datanotebook
    container_name: q-datanotebook
    environment:
      - JUPYTER_TOKEN= # Set a token if desired, or leave blank to disable token authentication
    networks:
      - q-iceberg
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/pydata/work # Mounts a local folder for persistent notebook storage

networks:
  q-iceberg: